spring:
  h2:
    console:
      enabled: true


  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/shop5
      username: root
      password: myoung1249!

mybatis:
  mapper-locations:
    - mappers/*.xml